<aside>
            <div class="l-sidebar_wrapper">
                <div class="l-sidebar_contents">
                    <h2>Menu</h2>
                    <section>
                        <h3>バーガー</h3>
                        <ul>
                            <li>ハンバーガー</li>
                            <li>チーズバーガー</li>
                            <li>テリヤキバーガー</li>
                            <li>アボカドバーガー</li>
                            <li>フィッシュバーガー</li>
                            <li>ベーコンバーガー</li>
                            <li>チキンバーガー</li>
                        </ul>
                    </section>
                    <section>
                        <h3>サイド</h3>
                        <ul>
                            <li>ポテト</li>
                            <li>サラダ</li>
                            <li>ナゲット</li>
                            <li>コーン</li>
                        </ul>
                    </section>
                    <section>
                        <h3>ドリンク</h3>
                        <ul>
                            <li>コーラ</li>
                            <li>ファンタ</li>
                            <li>オレンジ</li>
                            <li>アップル</li>
                            <li>紅茶（Ice/Hot）</li>
                            <li>コーヒー（Ice/Hot）</li>
                        </ul>
                    </section>
                </div>
            </div>
        </aside>
    </div>